name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy theme on server
        id: deploy_theme
        uses: Pendect/action-rsyncer@v1.1.0
        env:
          DEPLOY_KEY: ${{ secrets.VPS_PRIVATE_KEY }}
        with:
          flags: '-avc --delete'
          src: './'
          dest: '${{ secrets.VPS_USERNAME }}@"${{ secrets.VPS_HOST }}":/var/www/html/'

#      - name: Copy files to VPS
#        uses: ./actions-runner/appleboy/scp-action@v0.1.4
#        with:
#          host: ${{ secrets.VPS_HOST }}
#          username: ${{ secrets.VPS_USERNAME }}
#          key: ${{ secrets.VPS_PRIVATE_KEY }}
#          port: ${{ secrets.VPS_PORT }}
#          source: ./
#          target: /var/www/html/

      - name: Set permissions
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            chmod -R 777 /var/www/html/

      - name: Run PHP Yii migrate
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/html/
            COMPOSER_ALLOW_SUPERUSER=1 composer install
            php yii migrate